name: Azure Naming Tool - Build and deploy to an Azure Web App
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AZURE_WEBAPP_NAME: ''
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'
jobs:
  build:
    defaults:
      run:
        working-directory: src
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4.1.2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget-
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Publish
      run: dotnet publish --no-build --no-restore -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-myapp
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ready/AzNamingTool
    needs: [build]
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: dotnet-myapp
      - name: Deploy as WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        
